### ISSUE TITLE
Disk cache request entity too large

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlockServer#485]
```
PayloadTooLargeError: request entity too large
    at readStream (/usr/src/app/node_modules/raw-body/index.js:155:17)
    at getRawBody (/usr/src/app/node_modules/raw-body/index.js:108:12)
    at read (/usr/src/app/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/usr/src/app/node_modules/body-parser/lib/types/json.js:135:5)
    at handleReturn (/usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at jsonParser (/usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /usr/src/app/dist/routes/getItem.js:25:46
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/dist/routes/getItem.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by mchangrh** [comment]
express default body size is 100k, is that what's going on here or is disk cache using another interface

**Comment by ajayyy** [comment]
https://github.com/ajayyy/DiskCache/commit/c491308327c72944aaf457aa9cc19e85e412e649
