### ISSUE TITLE
Reconnect when db terminates connection

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlockServer#487]
```
Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:641:28)
    at Connection.emit (node:events:527:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:57:12)
    at Socket.emit (node:events:527:28)
    at TCP.<anonymous> (node:net:709:12)
Emitted 'error' event on Client instance at:
    at Client._handleErrorEvent (/usr/src/app/node_modules/pg/lib/client.js:319:10)
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:149:16)
    at Object.onceWrapper (node:events:641:28)
    [... lines matching original stack trace ...]
    at TCP.<anonymous> (node:net:709:12
```

**Comment by ajayyy** [comment]
Maybe this is why the connection is terminating

```
2022-07-19 19:00:15.913 UTC [31994] LOG:  could not receive data from client: Connection reset by peer
2022-07-19 19:00:16.119 UTC [25715] LOG:  could not receive data from client: Connection reset by peer
2022-07-19 19:00:16.119 UTC [25713] LOG:  could not receive data from client: Connection reset by peer
2022-07-19 19:00:16.119 UTC [25714] LOG:  could not receive data from client: Connection reset by peer
2022-07-19 19:00:16.119 UTC [25712] LOG:  could not receive data from client: Connection reset by peer
2022-07-19 19:00:16.127 UTC [25711] LOG:  could not receive data from client: Connection reset by peer
2022-07-19 19:00:16.131 UTC [25710] LOG:  could not receive data from client: Connection reset by peer
2022-07-19 19:04:01.008 UTC [1873] LOG:  could not receive data from client: Connection reset by peer
2022-07-19 19:06:22.363 UTC [23700] LOG:  could not receive data from client: Connection timed out
2022-07-19 19:10:19.698 UTC [31856] ERROR:  canceling statement due to conflict with recovery
2022-07-19 19:10:19.698 UTC [31856] DETAIL:  User query might have needed to see row versions that must be removed.
```

**Comment by ajayyy** [comment]
> HINT:  In a moment you should be able to reconnect to the database and repeat your command.

This needs to be handled and it needs to retry with a non-repl node

**Comment by ajayyy** [comment]
> Switching back to not using repls for now

Nevermind, it doesn't like that

**Comment by ajayyy** [comment]
It's possible to extend the timeout, or make it indefinite, but it could lead to streaming being paused for a long time. The default timeout is 30 seconds, but should be fine for the current usecase.

https://stackoverflow.com/questions/14592436/postgresql-error-canceling-statement-due-to-conflict-with-recovery

I've added code that should catch the error, and made it only use replicas for short queries, which should solve this issue. If not, a retry could be added for exceptions depending on exception type.

**Comment by ajayyy** [comment]
Added retrying with the non replica for this specific error
