### ISSUE TITLE
Liveliness check still successful during certain errors that break the whole pod

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlockServer#516]
```
Entrypoint script
 ERROR 2022-10-24T12:48:44.719Z:   error: pgbouncer cannot connect to server
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 55,
  severity: 'FATAL',
  code: '08P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: undefined,
  line: undefined,
  routine: undefined
} 
```

This error should cause the http server to stop causing k8s to restart the pod automatically

**Comment by ajayyy** [comment]
176f2ce7b9ff57671433e3b0dfdf88a162f088b2
