### ISSUE TITLE
it throws a syntax error if i try to run the tests or try to start the server

### ISSUE THREAD

**Issue by hannescam** [ajayyy/SponsorBlockServer#522]
the log:
```
hannes@Hannes-Satis-Server:~/SponsorBlockServer$ npm -v
8.19.2
hannes@Hannes-Satis-Server:~/SponsorBlockServer$ npm test

> sponsor_block_server@0.1.0 test
> npm run tsc && ts-node test/test.ts


> sponsor_block_server@0.1.0 tsc
> tsc -p tsconfig.json

/home/hannes/SponsorBlockServer/src/config.ts:188
        if (redisConfig.socket?.host && redisConfig.enabled === undefined) {
                               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module.m._compile (/home/hannes/SponsorBlockServer/node_modules/ts-node/src/index.ts:1597:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/home/hannes/SponsorBlockServer/node_modules/ts-node/src/index.ts:1600:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hannes/SponsorBlockServer/test/test.ts:4:1)
hannes@Hannes-Satis-Server:~/SponsorBlockServer$
```

**Comment by ajayyy** [comment]
Looks like an old version of node

**Comment by hannescam** [comment]
how can i upgrade that?

**Comment by hannescam** [comment]
it now throws a different error:
```
hannes@Hannes-Satis-Server:~/SponsorBlockServer$ npm start

> sponsor_block_server@0.1.0 start
> ts-node src/index.ts

/home/hannes/SponsorBlockServer/src/config.ts:10
export const config: SBSConfig = JSON.parse(fs.readFileSync(configFile).toString("utf8"));
                                      ^
SyntaxError: Unexpected token / in JSON at position 6
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/hannes/SponsorBlockServer/src/config.ts:10:39)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module.m._compile (/home/hannes/SponsorBlockServer/node_modules/ts-node/src/index.ts:1597:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/home/hannes/SponsorBlockServer/node_modules/ts-node/src/index.ts:1600:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
hannes@Hannes-Satis-Server:~/SponsorBlockServer$ 
```

**Comment by mchangrh** [comment]
looks like you forgot to take out the comments in config.json
